[project]
name = "demo22"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.13.0",
    "httpx>=0.28.1",
    "mcp>=1.7.1",
    "python-dotenv>=1.1.0",
]
